version: '3.8'
services:
  get_custom_account:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      PORT: 3000
    command: ["node", "OpenAPI/1234.opent1-getCustomAccount-s-rest-v1.js"]

  initiating_transfer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:3001"
    environment:
      PORT: 3001
    command: ["node", "OpenAPI/1234.opent1-initiatingTransfer-s-rest-v1.js"]

  management_credit_products:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:3002"
    environment:
      PORT: 3002
    command: ["node", "OpenAPI/1234.opent1-ManagementCreditProducts-s-rest-v1.js"]

  transfers_of_funds:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:3003"
    environment:
      PORT: 3003
    command: ["node", "OpenAPI/1234.opent1-transfersOfFunds-s-rest-v1.js"]

  emission_requests:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:3004"
    environment:
      PORT: 3004
    command: ["node", "PartnerAPI/Cards/1234.opent1-EmissionRequests-s-rest-v1.js"]

  information_requests:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:3005"
    environment:
      PORT: 3005
    command: ["node", "PartnerAPI/Cards/1234.opent1-InformationRequests-s-rest-v1.js"]

  operation_requests:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:3006"
    environment:
      PORT: 3006
    command: ["node", "PartnerAPI/Cards/1234.opent1-OperationRequests-s-rest-v1.js"]

  payment_basic_scenario:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:3007"
    environment:
      PORT: 3007
    command: ["node", "PartnerAPI/Payments/1234.opent1-PaymentBasicScenario-s-rest-v1.js"]

  payment_mobile_operator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:3008"
    environment:
      PORT: 3008
    command: ["node", "PartnerAPI/Payments/1234.opent1-PaymentMobileOperator-s-rest-v1.js"]

  payment_of_fines:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:3009"
    environment:
      PORT: 3009
    command: ["node", "PartnerAPI/Payments/1234.opent1-PaymentOfFines-s-rest-v1.js"]

  search_providers:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:3010"
    environment:
      PORT: 3010
    command: ["node", "PartnerAPI/Payments/1234.opent1-SearchProviders-s-rest-v1.js"]

  cash_loans:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:3011"
    environment:
      PORT: 3011
    command: ["node", "PartnerAPI/1234.opent1-CashLoans-s-rest-v1.js"]

  lead_operations:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8092:3012"
    environment:
      PORT: 3012
    command: ["node", "PartnerAPI/1234.opent1-LeadOperations-s-rest-v1.js"]

  payment_bonus_points:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8093:3013"
    environment:
      PORT: 3013
    command: ["node", "PartnerAPI/1234.opent1-PaymentBonusPoints-s-rest-v1.js"]

